#!/bin/sh

if [ $SHELL = "/bin/bash" ]
then
    echo "" >> $HOME/.bashrc
    echo "# cadCAD CLI" >> $HOME/.bashrc
    echo "export PATH=\$PATH:$PWD/bin" >> $HOME/.bashrc
fi

echo "Installed! Please restart your terminal to take effect."