#!/bin/sh

if [ $SHELL = "/bin/bash" ]
then
    echo "" >> $HOME/.bashrc
    echo "# cadCAD CLI" >> $HOME/.bashrc
    echo "export PATH=\$PATH:$PWD/bin" >> $HOME/.bashrc
    export PATH=$PATH:$PWD/bin
fi

echo "Installed! You may need to restart your terminal to take effect."